sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
  - secure: UystVKejSchL4ifStWLx7Uz8r8dkFGJSGcLI5+9Ky1qO9ukaAF/LspV5lDOvfxNBtj8nRQeC4Iy1HhdalCPZazV1/2XtYUQhRem3yQy5Af0Yzcr4PGHIEf1RKr4ofHyAneLr40W0SqFaboTHyjKO/zjA1TakmDtR5aUR0tw2murKFo0ts7tbYcWTyE8L1KZ+VJhzvgfel70jzTDQ932FhaiQyXhbVljpedZQrIi84K22ADA5k/rgd/2HW2HgpFD+271LSyvPTSeCvUGeK6DwC0fbcAz1iYZQQZqhzAA1jbKiMm7wrgtNVBBl5IkemxEjar6+TKhmxyVPtOnevyCy0qZmUtgMdmVTwVp70bKzjJkBdcHMK295ap2mwawSWDuCZuPaKvn8qUkYhKlkAKVX/uD3r7fJ696c4KFkBHXyfHE0VliLJpCxoxpDrlDK6Btm3GjlAxv8UdKIuXQgttuPH8XlxCH9rPvHj1a5aMZwfbXta57E16W4slPO9mI9Y0xaQiiJQurZ1lFqyvUYGKcwRNoTMwoclLCLM4a8q+JP3i06dmJhBuJXfNo4NFkwx4NcIjVUb2VcvFhN8UgkJYQRC+cJYpoCbN0saCeQpWUGBqqMxYacMuM6YdpohLMxCoENbvq0my0Ff/YGXF01+AExvo/0Azhc/WAkw47HhVSgXKY=
  - secure: AEIgULeAAE1iWkORRsj+NDkUNeLUUlHYm5zXLkqTX6/vorG1Qpb7vloRGR1o4zN3kY0gBmo3tmmEpNJTkUlR6HqDl9PzbJYCB5g1z+Z6qEizQU28g4e8kYHhdfMuEWkcPfSBud9/geav2Of30LlynC3yU06UE/FAXXQzVrcQ4yd65JIyyKbWUWWjOyrSJxDpXDr94C5z9QPxN9BdLuSbLObckbQLapHHzGSRatGDkRaNy/wo9ZqsgCU5knYUavLHbP0BVWT3HhZ+nGM4JQdBtfpSBTwCHqeELegxMPuSodEVU2PBCGuBJD3qXDV1VbuxgFRITzKM/gcFl6X/sI0DnQUeSX2FBqnu0cq/J0jPdBy/MQi/JubPNuW28/WIO6Y4p4p4/XSOMaCIonBQIKvzFPbXo1coQlfYKiqiYIjAJBh3Lo22XqHxlnhoaEv1aB+wH8Vn4SO4lQwuf+GYFu1qUWcmo55Vo+//PP/sTz7ThKnRw5jixcACO57Y7ZaDSDE2Ah71A4kjpJtLxvdhVmorMqLn0ykajRqN02fyjrv/ffxSXuYRRMMT1NbCBr1AxPi8yC6DQ1HX1g2ZyZE5L9SIxJGXW4746/3sKx9jubo/d1708M8HtunRdqmBGwC3YHr0yaLVLrIakWTdzo95yaWljPaZDwGIZIaYr7939ZUdzVQ=
branches:
  only: master
after_success:
- "./gradlew remoteDeploy"
